# Site settings
title: Juanyan's Time Machine
email: jasperlee1118@gmail.com
description: Mostly Data Science stuffs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

include: ["_pages"]

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: Jaspereclipse
permalink: /:title/
# this is the url root of the view source link on the footer page.
# viewsourceroot:
# this is the url root of the create page link on the footer page.
# newsourceroot:
#########################################
disqus_shortname: jaspereclipse
disqus_url: "https://jaspereclipse.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
highlighter: rouge
# highlighter: false
